version: "3.1"
services:
  postgres: 
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: postgres-dbname 
    ports:
      - 5432:5432